stages:
  - test

before_script:
  - docker -v
  - docker info
  - python -V
  - ansible --version
  - molecule --version
  - pip install -r requirements.txt

.molecule-default:
  stage: test
  script:
    - molecule test --all
  tags:
    - docker

ansible-3:
  extends: .molecule-default
  image: leandelivery/docker-ansible-ci:ansible-3
