---
  - name: "(helpers/issue) Issue cert for {{ domain }}"
    hashivault_write:
      mount_point: "{{ vault_cert_mount_point }}"
      secret: "{{ vault_cert_issuer }}"
      data:
        common_name: "{{ domain }}"
        organization: "{{ infraunlimited_vault_organization }}"
        ou: "{{ infraunlimited_vault_ou }}"
        ttl: "{{ infraunlimited_vault_cert_ttl }}"
        format: "{{ infraunlimited_vault_cert_format | default ('pem_bundle') }}"
        ip_sans: "{{ ip_sans | default(omit) }}"
    register: vault_cert_issue_done
    delegate_to: localhost

  - name: (helpers/issue) Report from hashivault
    debug:
      msg: "{{ vault_cert_issue_done }}"
    when: vault_cert_issue_done.changed
    delegate_to: localhost
