---
  - include_role:
      name: brianshumate.vault

  - import_tasks: bootstrap.yml
    delegate_to: localhost

  - import_tasks: audit.yml
    delegate_to: localhost

  - import_tasks: users.yml
    delegate_to: localhost

  - import_tasks: secrets.yml
    when: infraunlimited_vault_secret is defined

  - import_tasks: pki.yml
    when: infraunlimited_vault_pki is defined
