---
  - name: configure Root CA
    import_tasks: configure_pki.yml
    vars:
      item: "{{ infraunlimited_vault_pki.ca.root }}"

  - name: configure Int CA
    include_tasks: configure_pki.yml
    with_items: "{{ infraunlimited_vault_pki.ca.intermediate }}"

  - import_tasks: check_ca.yml
    vars:
      vault_needed_ca: "{{ infraunlimited_vault_pki.ca.root.mount_point }}"

  - import_tasks: create_root_ca.yml
    when: not vault_nedeed_ca_exists

  - include_tasks: create_intermediate_ca.yml
    with_items: "{{ infraunlimited_vault_pki.ca.intermediate }}"
