---
  - name: (Secrets) Enable/Disable secret engines
    hashivault_secret_engine:
      backend: kv
      options:
        version: "{{ item.value.version }}"
      name: "{{ item.value.mount_point }}"
      description: "{{ item.value.description }}"
      state: "{{ item.value.state | default('enabled') }}"
      config: "{{ item.value.config | default({}) }}"
    with_dict: "{{ infraunlimited_vault_secret.engines }}"
