---
  - name: Enable secret engines
    hashivault_secret_engine:
      backend: kv
      options:
        version: "{{ item.value.version }}"
      name: "{{ item.value.mount_point }}"
      description: "{{ item.value.description }}"
      state: enabled
      config:
        max_lease_ttl: 157680000 # 5 years 
        default_lease_ttl: 31536000 # 1 year
    with_dict: "{{ infraunlimited_vault_secret.engines }}"
    delegate_to: localhost
