---
  - name: (helpers/upload) Upload secret {{ vault_mount_point }}/{{ vault_secret_directory }}/{{ vault_secret_name }} to Hashivault
    hashivault_write:
      mount_point: "{{ vault_mount_point }}"
      secret: "{{ vault_secret_directory }}/{{ vault_secret_name }}"
      version: "{{ vault_version }}"
      data: "{{ vault_uploaded_data }}"
    register: secret_uploaded
    delegate_to: localhost

  - name: (helpers/upload) Report from hashivault
    debug:
      msg: "{{ secret_uploaded }}"
    when: secret_uploaded.changed
    delegate_to: localhost

  - set_fact:
      secret_uploaded: false
    when: secret_uploaded.changed
    delegate_to: localhost
