---
- name: Cleanup
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
  - name: (Cleanup) Remove credentials file
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "{{ infraunlimited_vault_admin_creds_file }}"
