---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Attach to target network
    docker_network:
      name: "{{ lookup('env', 'NETWORK') }}"
      appends: true
      connected:
        - "{{ lookup('env', 'TARGET_HOSTNAME') }}"
