---
- name: Verify
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
  - name: (Verify) Get Vault status
    hashivault_status:
    register: vault_status

  - name: (Verify) Check if Vault initialized
    assert:
      that:
        - vault_status.status.initialized
      fail_msg: Vault is not initialized

  - name: (Verify) Can write secret (with config)
    hashivault_write:
      mount_point: secret_infra
      secret: secret1
      version: 2
      data:
        msg: "with config"
