---

.container_name: &container_name ${HOSTNAME}-centos7-default
.network_name: &network_name ${HOSTNAME}-network-default
.vault_addr: &vault_addr http://${HOSTNAME}-centos7-default:8200

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: *container_name
    image: leandelivery/docker-systemd:centos7
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: '/usr/sbin/init'
    networks:
      - name: *network_name
provisioner:
  name: ansible
  env:
    NETWORK: *network_name
    VAULT_ADDR: *vault_addr
  playbooks:
    prepare: ../resources/prepare.yml
    cleanup: ../resources/cleanup.yml
    verify: ../resources/verify.yml
  lint: |
    ansible-lint
verifier:
  name: ansible
