Vagrant.configure("2") do |config|
  config.vm.box = "infra-centos7"

  config.ssh.forward_agent = true
  config.vm.network "forwarded_port", guest: 22, host: 2222, disabled: true
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder '..', '/vagrant/ansible', type: "sshfs"
  
  config.vm.define "vault" do |vault|
  vault.vm.network "forwarded_port", guest: 8200, host: 8200

    vault.vm.provision "ansible" do |provise|
      ENV['ANSIBLE_ROLES_PATH'] = '../..'
      ENV['VAULT_ADDR'] = 'http://127.0.0.1:8200'
      provise.galaxy_role_file = "../requirements.yml"
      provise.playbook = "play.yml"
      provise.tags = ENV['TAGS']
      provise.verbose = ENV['VERBOSE']

      provise.raw_arguments = [ '-e',  '@../vars/brianshumate.vault.yml' ]
      # Vagrant-specific vars
      provise.extra_vars = {
        'infraunlimited_vault_admin_creds_file' => '/tmp/vagrant_infra_user_creds_file.yml',
        'infraunlimited_vault_creds_file' => '/tmp/vagrant_infra_vault_creds_file.yml',
        'infraunlimited_vault_admin_policy_file' => '../files/admin-policy.hcl'
      }
      provise.become = true
    end
  end
end
